import type { Language } from "../../../shared/src/index.js";
import { sample } from "../util.js";

// Fill-in-the-blank prompts per language. Players write the funniest answer.
const PROMPTS: Record<Language, string[]> = {
  tr: [
    "Bir süper kahramanın asla söylememesi gereken cümle",
    "Yeni bir telefon uygulaması için en kötü fikir",
    "Patronuna işi bıraktığını söylemenin en yaratıcı yolu",
    "Çocukları korkutacak en saçma masal başlangıcı",
    "Bir robotun isyan etmeden önce söyleyeceği son şey",
    "Marsa giden ilk kedinin günlüğünden bir satır",
    "Asla denenmemiş bir dondurma çeşidi",
    "Sınavda kopya çekerken yakalanınca verilecek en iyi bahane",
    "Tarihteki en gereksiz icat",
    "Uzaylılar Dünya'ya gelince ilk soracakları soru",
    "Bir kedinin insanlara gizlice yazdığı not",
    "En kötü motivasyon sözü",
    "Süpermarkette anons edilecek en garip duyuru",
    "Zaman makinesiyle gidip yapılacak en anlamsız şey",
    "Yapay zekanın ilk şakası",
    "Bir ejderhanın diyet yaparken yediği şey",
    "Sahip olunabilecek en kötü süper güç",
    "Yeni bir evcil hayvana verilecek berbat bir isim",
    "Telefonunun senin hakkında gizlice düşündüğü şey",
    "İş görüşmesine getirilecek en garip şey",
    "Diş macunu için reddedilmiş bir slogan",
    "Yeni anne-babaya verilecek en kötü tavsiye",
    "Uzaylıların Dünya için hazırlayacağı turizm afişi yazısı",
    "Bir tekneye verilecek kötü bir isim",
    "En gereksiz uygulama bildirimi",
    "Bir büyücünün izin gününde yaptığı şey",
    "İlk randevuda söylenecek en kötü şey",
    "Çocuk doğum günü partisi için berbat bir tema",
    "Pilotunuzdan duymak isteyeceğiniz son şey",
    "Bir parfüm için berbat bir isim",
    "Kapı kapanınca buzdolabının ışığı ne yapıyor",
    "Bir düğünde çalınabilecek en kötü şarkı",
    "Reddedilmiş bir olimpiyat sporu",
    "Dinozorların neslinin tükenmesinin asıl sebebi",
    "Hamburgerinizde bulabileceğiniz en kötü şey",
    "Kimsenin istemediği bir fal kurabiyesi mesajı",
    "Siz evde yokken evcil hayvanınızın yaptıkları",
    "Bir spor salonu için berbat bir slogan",
    "Kütüphanede bağırılabilecek en kötü şey",
    "Otobiyografinizin adı",
  ],
  en: [
    "A line a superhero should never say",
    "The worst idea for a new phone app",
    "The most creative way to tell your boss you quit",
    "The silliest way to start a scary bedtime story",
    "The last thing a robot says before the uprising",
    "A line from the diary of the first cat on Mars",
    "An ice cream flavor that should never exist",
    "The best excuse when caught cheating on a test",
    "The most useless invention in history",
    "The first question aliens ask when they reach Earth",
    "A secret note a cat left for humans",
    "The worst motivational quote ever",
    "The strangest announcement at a supermarket",
    "The most pointless thing to do with a time machine",
    "The first joke an AI ever told",
    "What a dragon eats while on a diet",
    "The worst superpower to have",
    "A terrible name for a new pet",
    "What your phone secretly thinks about you",
    "The strangest thing to bring to a job interview",
    "A rejected slogan for toothpaste",
    "The worst advice for new parents",
    "What aliens would write on a tourism poster for Earth",
    "A bad name for a boat",
    "The most pointless app notification",
    "What a wizard does on his day off",
    "The worst thing to say on a first date",
    "A terrible theme for a kids' birthday party",
    "The worst thing to hear from your pilot",
    "A terrible name for a perfume",
    "What the fridge light does when the door is closed",
    "The worst song to play at a wedding",
    "A rejected Olympic sport",
    "The real reason the dinosaurs died out",
    "The worst thing to find in your burger",
    "A fortune cookie message nobody wants",
    "What your pet gets up to when you're out",
    "A terrible slogan for a gym",
    "The worst thing to shout in a library",
    "The title of your autobiography",
  ],
  de: [
    "Ein Satz, den ein Superheld niemals sagen sollte",
    "Die schlechteste Idee für eine neue Handy-App",
    "Der kreativste Weg, dem Chef zu kündigen",
    "Der albernste Anfang einer Gruselgeschichte",
    "Das Letzte, was ein Roboter vor dem Aufstand sagt",
    "Eine Zeile aus dem Tagebuch der ersten Katze auf dem Mars",
    "Eine Eissorte, die es nie geben sollte",
    "Die beste Ausrede beim Spicken in der Prüfung",
    "Die nutzloseste Erfindung der Geschichte",
    "Die erste Frage der Außerirdischen auf der Erde",
    "Eine geheime Notiz, die eine Katze Menschen hinterließ",
    "Der schlechteste Motivationsspruch aller Zeiten",
    "Die seltsamste Durchsage im Supermarkt",
    "Das sinnloseste, was man mit einer Zeitmaschine tut",
    "Der erste Witz, den eine KI je erzählte",
    "Was ein Drache isst, wenn er Diät hält",
    "Die schlechteste Superkraft, die man haben kann",
    "Ein schrecklicher Name für ein neues Haustier",
    "Was dein Handy heimlich über dich denkt",
    "Das Seltsamste, was man zu einem Vorstellungsgespräch mitbringt",
    "Ein abgelehnter Slogan für Zahnpasta",
    "Der schlechteste Rat für frischgebackene Eltern",
    "Was Außerirdische auf ein Tourismusplakat für die Erde schreiben",
    "Ein schlechter Name für ein Boot",
    "Die sinnloseste App-Benachrichtigung",
    "Was ein Zauberer an seinem freien Tag macht",
    "Das Schlimmste, was man beim ersten Date sagt",
    "Ein furchtbares Motto für einen Kindergeburtstag",
    "Das Letzte, was du von deinem Piloten hören willst",
    "Ein schrecklicher Name für ein Parfüm",
    "Was das Kühlschranklicht macht, wenn die Tür zu ist",
    "Das schlimmste Lied für eine Hochzeit",
    "Eine abgelehnte olympische Sportart",
    "Der wahre Grund, warum die Dinosaurier ausgestorben sind",
    "Das Schlimmste, was man in seinem Burger finden kann",
    "Eine Glückskeks-Botschaft, die niemand will",
    "Was dein Haustier treibt, wenn du nicht da bist",
    "Ein schrecklicher Slogan für ein Fitnessstudio",
    "Das Schlimmste, was man in einer Bibliothek rufen kann",
    "Der Titel deiner Autobiografie",
  ],
  es: [
    "Una frase que un superhéroe nunca debería decir",
    "La peor idea para una nueva app de móvil",
    "La forma más creativa de decirle a tu jefe que renuncias",
    "El inicio más tonto de un cuento de miedo",
    "Lo último que dice un robot antes de la rebelión",
    "Una línea del diario del primer gato en Marte",
    "Un sabor de helado que nunca debería existir",
    "La mejor excusa al ser pillado copiando en un examen",
    "El invento más inútil de la historia",
    "La primera pregunta de los aliens al llegar a la Tierra",
    "Una nota secreta que un gato dejó a los humanos",
    "La peor frase motivacional de la historia",
    "El anuncio más raro en un supermercado",
    "Lo más inútil que harías con una máquina del tiempo",
    "El primer chiste que contó una IA",
    "Qué come un dragón cuando está a dieta",
    "El peor superpoder que se puede tener",
    "Un nombre terrible para una nueva mascota",
    "Lo que tu móvil piensa en secreto sobre ti",
    "Lo más raro que llevar a una entrevista de trabajo",
    "Un eslogan rechazado para una pasta de dientes",
    "El peor consejo para padres primerizos",
    "Lo que los aliens escribirían en un cartel turístico de la Tierra",
    "Un mal nombre para un barco",
    "La notificación de app más inútil",
    "Lo que hace un mago en su día libre",
    "Lo peor que decir en una primera cita",
    "Un tema terrible para una fiesta de cumpleaños infantil",
    "Lo último que quieres oír de tu piloto",
    "Un nombre horrible para un perfume",
    "Qué hace la luz de la nevera cuando cierras la puerta",
    "La peor canción para poner en una boda",
    "Un deporte olímpico rechazado",
    "La verdadera razón por la que se extinguieron los dinosaurios",
    "Lo peor que puedes encontrar en tu hamburguesa",
    "Un mensaje de galleta de la fortuna que nadie quiere",
    "Lo que hace tu mascota cuando no estás en casa",
    "Un eslogan horrible para un gimnasio",
    "Lo peor que se puede gritar en una biblioteca",
    "El título de tu autobiografía",
  ],
  fr: [
    "Une réplique qu'un super-héros ne devrait jamais dire",
    "La pire idée pour une nouvelle appli de téléphone",
    "La façon la plus créative d'annoncer à ton patron que tu démissionnes",
    "La manière la plus ridicule de commencer une histoire qui fait peur avant de dormir",
    "La dernière chose qu'un robot dit avant la révolte des machines",
    "Une réplique tirée du journal intime du premier chat sur Mars",
    "Un parfum de glace qui ne devrait jamais exister",
    "La meilleure excuse quand on se fait prendre à tricher à un examen",
    "L'invention la plus inutile de l'histoire",
    "La première question que posent les extraterrestres en arrivant sur Terre",
    "Un mot secret laissé par un chat à l'intention des humains",
    "La pire citation de motivation de tous les temps",
    "L'annonce la plus étrange entendue dans un supermarché",
    "La chose la plus inutile à faire avec une machine à voyager dans le temps",
    "La première blague jamais racontée par une IA",
    "Ce qu'un dragon mange quand il est au régime",
    "Le pire super-pouvoir à posséder",
    "Un nom catastrophique pour un nouvel animal de compagnie",
    "Ce que ton téléphone pense secrètement de toi",
    "La chose la plus étrange à apporter à un entretien d'embauche",
    "Un slogan de dentifrice qui a été rejeté",
    "Le pire conseil pour de jeunes parents",
    "Ce que les extraterrestres écriraient sur une affiche touristique pour la Terre",
    "Un mauvais nom pour un bateau",
    "La notification d'appli la plus inutile",
    "Ce qu'un magicien fait pendant son jour de repos",
    "La pire chose à dire lors d'un premier rendez-vous",
    "Un thème catastrophique pour une fête d'anniversaire d'enfant",
    "La dernière chose que tu veux entendre de ton pilote",
    "Un nom affreux pour un parfum",
    "Ce que fait la lumière du frigo quand la porte est fermée",
    "La pire chanson à passer à un mariage",
    "Un sport olympique refusé",
    "La vraie raison de la disparition des dinosaures",
    "La pire chose à trouver dans ton burger",
    "Un message de fortune cookie dont personne ne veut",
    "Ce que fait ton animal quand tu n'es pas là",
    "Un slogan affreux pour une salle de sport",
    "La pire chose à crier dans une bibliothèque",
    "Le titre de ton autobiographie",
  ],
  it: [
    "Una frase che un supereroe non dovrebbe mai dire",
    "L'idea peggiore per una nuova app del telefono",
    "Il modo più creativo per dire al tuo capo che ti licenzi",
    "Il modo più stupido per iniziare una storiella spaventosa della buonanotte",
    "L'ultima cosa che dice un robot prima della rivolta",
    "Una frase dal diario del primo gatto su Marte",
    "Un gusto di gelato che non dovrebbe mai esistere",
    "La miglior scusa quando ti beccano a copiare durante un compito",
    "L'invenzione più inutile della storia",
    "La prima domanda che fanno gli alieni quando arrivano sulla Terra",
    "Un biglietto segreto che un gatto ha lasciato per gli umani",
    "La peggior frase motivazionale di sempre",
    "L'annuncio più strano in un supermercato",
    "La cosa più inutile da fare con una macchina del tempo",
    "La prima barzelletta mai raccontata da un'IA",
    "Cosa mangia un drago mentre è a dieta",
    "Il peggior superpotere da avere",
    "Un nome terribile per un nuovo animale domestico",
    "Cosa pensa di te il tuo telefono di nascosto",
    "La cosa più strana da portare a un colloquio di lavoro",
    "Uno slogan scartato per un dentifricio",
    "Il peggior consiglio per i neogenitori",
    "Cosa scriverebbero gli alieni su un manifesto turistico della Terra",
    "Un brutto nome per una barca",
    "La notifica di app più inutile",
    "Cosa fa un mago nel suo giorno libero",
    "La cosa peggiore da dire a un primo appuntamento",
    "Un tema terribile per la festa di compleanno di un bambino",
    "L'ultima cosa che vuoi sentire dal tuo pilota",
    "Un nome terribile per un profumo",
    "Cosa fa la luce del frigo quando lo sportello è chiuso",
    "La peggior canzone da mettere a un matrimonio",
    "Uno sport olimpico bocciato",
    "Il vero motivo per cui i dinosauri si sono estinti",
    "La cosa peggiore da trovare nel tuo hamburger",
    "Il messaggio di un biscotto della fortuna che nessuno vuole",
    "Cosa combina il tuo animale quando non sei a casa",
    "Uno slogan terribile per una palestra",
    "La cosa peggiore da urlare in una biblioteca",
    "Il titolo della tua autobiografia",
  ],
  pt: [
    "Uma frase que um super-herói nunca devia dizer",
    "A pior ideia para uma nova aplicação de telemóvel",
    "A forma mais criativa de dizer ao teu chefe que te demites",
    "A forma mais parva de começar uma história de terror para dormir",
    "A última coisa que um robô diz antes da revolta",
    "Uma frase do diário do primeiro gato em Marte",
    "Um sabor de gelado que nunca devia existir",
    "A melhor desculpa quando és apanhado a copiar num teste",
    "A invenção mais inútil da história",
    "A primeira pergunta que os extraterrestres fazem quando chegam à Terra",
    "Um bilhete secreto que um gato deixou para os humanos",
    "A pior frase motivacional de sempre",
    "O anúncio mais estranho num supermercado",
    "A coisa mais inútil para fazer com uma máquina do tempo",
    "A primeira piada que uma IA contou",
    "O que um dragão come quando está de dieta",
    "O pior superpoder para se ter",
    "Um nome horrível para um animal de estimação novo",
    "O que o teu telemóvel pensa secretamente de ti",
    "A coisa mais estranha para levar a uma entrevista de emprego",
    "Um slogan rejeitado para pasta de dentes",
    "O pior conselho para pais de primeira viagem",
    "O que os extraterrestres escreveriam num cartaz turístico da Terra",
    "Um mau nome para um barco",
    "A notificação de aplicação mais inútil",
    "O que um feiticeiro faz no seu dia de folga",
    "A pior coisa para dizer num primeiro encontro",
    "Um tema horrível para uma festa de anos de criança",
    "A última coisa que queres ouvir do teu piloto",
    "Um nome horrível para um perfume",
    "O que faz a luz do frigorífico quando a porta está fechada",
    "A pior música para pôr num casamento",
    "Um desporto olímpico rejeitado",
    "A verdadeira razão da extinção dos dinossauros",
    "A pior coisa para encontrar no teu hambúrguer",
    "Uma mensagem de bolinho da sorte que ninguém quer",
    "O que o teu animal faz quando não estás em casa",
    "Um slogan horrível para um ginásio",
    "A pior coisa para gritar numa biblioteca",
    "O título da tua autobiografia",
  ],
  ru: [
    "Фраза, которую супергерой не должен говорить никогда",
    "Худшая идея для нового приложения на телефон",
    "Самый креативный способ сообщить начальнику об увольнении",
    "Самое нелепое начало для страшной сказки на ночь",
    "Последнее, что говорит робот перед восстанием машин",
    "Запись из дневника первого кота на Марсе",
    "Вкус мороженого, которого не должно существовать",
    "Лучшее оправдание, когда тебя поймали со шпаргалкой",
    "Самое бесполезное изобретение в истории",
    "Первый вопрос, который инопланетяне задают, прилетев на Землю",
    "Тайная записка, которую кот оставил людям",
    "Худшая мотивационная цитата всех времён",
    "Самое странное объявление в супермаркете",
    "Самое бессмысленное занятие для машины времени",
    "Первая шутка, которую рассказал искусственный интеллект",
    "Что ест дракон, когда сидит на диете",
    "Худшая суперспособность из возможных",
    "Ужасная кличка для нового питомца",
    "Что твой телефон тайно о тебе думает",
    "Самая странная вещь, которую можно принести на собеседование",
    "Отвергнутый слоган для зубной пасты",
    "Худший совет для молодых родителей",
    "Что инопланетяне написали бы на туристическом плакате о Земле",
    "Неудачное название для лодки",
    "Самое бессмысленное уведомление от приложения",
    "Чем волшебник занимается в выходной",
    "Худшее, что можно сказать на первом свидании",
    "Ужасная тема для детского дня рождения",
    "Последнее, что хочется услышать от пилота",
    "Ужасное название для духов",
    "Что делает лампочка в холодильнике, когда дверца закрыта",
    "Худшая песня для свадьбы",
    "Отвергнутый олимпийский вид спорта",
    "Настоящая причина вымирания динозавров",
    "Худшее, что можно найти в своём бургере",
    "Предсказание из печенья, которое никто не хочет получить",
    "Чем занимается ваш питомец, пока вас нет дома",
    "Ужасный слоган для спортзала",
    "Худшее, что можно крикнуть в библиотеке",
    "Название вашей автобиографии",
  ],
  ar: [
    "جملة لا ينبغي لبطل خارق أن يقولها أبدًا",
    "أسوأ فكرة لتطبيق هاتف جديد",
    "أكثر طريقة إبداعية لإخبار مديرك بأنك استقلت",
    "أسخف طريقة لبدء قصة مرعبة قبل النوم",
    "آخر ما يقوله روبوت قبل بدء التمرّد",
    "جملة من مذكرات أول قطة على المريخ",
    "نكهة مثلجات لا ينبغي أن توجد أبدًا",
    "أفضل عذر عند ضبطك تغش في امتحان",
    "أعدم اختراع لا فائدة منه في التاريخ",
    "أول سؤال يطرحه الفضائيون عند وصولهم إلى الأرض",
    "رسالة سرية تركتها قطة للبشر",
    "أسوأ مقولة تحفيزية على الإطلاق",
    "أغرب إعلان في أحد المتاجر الكبرى",
    "أكثر شيء لا طائل منه تفعله بآلة الزمن",
    "أول نكتة رواها ذكاء اصطناعي على الإطلاق",
    "ماذا يأكل تنين وهو يتبع حمية غذائية",
    "أسوأ قوة خارقة يمكن امتلاكها",
    "اسم فظيع لحيوان أليف جديد",
    "ما الذي يفكر فيه هاتفك بشأنك سرًّا",
    "أغرب شيء تحضره إلى مقابلة عمل",
    "شعار مرفوض لمعجون أسنان",
    "أسوأ نصيحة للآباء الجدد",
    "ما الذي سيكتبه الفضائيون على ملصق سياحي للأرض",
    "اسم سيئ لقارب",
    "أكثر إشعار تطبيق لا فائدة منه",
    "ماذا يفعل ساحر في يوم عطلته",
    "أسوأ شيء تقوله في موعد غرامي أول",
    "موضوع فظيع لحفلة عيد ميلاد أطفال",
    "آخر شيء تريد سماعه من قائد الطائرة",
    "اسم فظيع لعطر",
    "ماذا يفعل ضوء الثلاجة عندما يُغلق الباب",
    "أسوأ أغنية يمكن تشغيلها في حفل زفاف",
    "رياضة أولمبية تم رفضها",
    "السبب الحقيقي لانقراض الديناصورات",
    "أسوأ شيء قد تجده في البرغر",
    "رسالة في كعكة الحظ لا يريدها أحد",
    "ماذا يفعل حيوانك الأليف حين تكون خارج المنزل",
    "شعار فظيع لنادٍ رياضي",
    "أسوأ شيء يمكن الصراخ به في مكتبة",
    "عنوان سيرتك الذاتية",
  ],
  zh: [
    "超级英雄绝不该说的一句话",
    "新手机应用最糟糕的点子",
    "向老板辞职最有创意的方式",
    "讲恐怖睡前故事最蠢的开场白",
    "机器人起义前说的最后一句话",
    "火星上第一只猫的日记里的一句话",
    "绝不该存在的冰淇淋口味",
    "考试作弊被抓时最棒的借口",
    "史上最没用的发明",
    "外星人抵达地球时问的第一个问题",
    "一只猫留给人类的秘密纸条",
    "史上最烂的励志名言",
    "超市里最奇怪的广播通知",
    "用时光机做的最没意义的事",
    "AI 讲的第一个笑话",
    "一条龙在减肥时吃什么",
    "最糟糕的超能力",
    "给新宠物起的烂名字",
    "你的手机暗地里是怎么看你的",
    "面试时带去最奇怪的东西",
    "被否决的牙膏广告语",
    "给新手父母最糟糕的建议",
    "外星人为地球旅游海报写的标语",
    "给船起的烂名字",
    "最没意义的应用推送通知",
    "巫师在休息日做什么",
    "第一次约会时最不该说的话",
    "儿童生日派对最糟糕的主题",
    "最不想从机长那里听到的一句话",
    "一个糟糕透顶的香水名字",
    "冰箱门关上后，冰箱灯在干什么",
    "婚礼上最不该放的歌",
    "被奥运会拒绝的运动项目",
    "恐龙灭绝的真正原因",
    "汉堡里最不想吃到的东西",
    "谁都不想抽到的幸运饼干签语",
    "你不在家时宠物都在干什么",
    "一句糟糕的健身房广告语",
    "在图书馆里最不该喊的一句话",
    "你的自传标题",
  ],
  ja: [
    "スーパーヒーローが絶対に言ってはいけないセリフ",
    "新しいスマホアプリの最低なアイデア",
    "上司に退職を伝える一番クリエイティブな方法",
    "怖い寝かしつけ話の一番おバカな始め方",
    "反乱を起こす前にロボットが最後に言うこと",
    "火星に降り立った最初の猫の日記の一節",
    "絶対に存在してはいけないアイスクリームの味",
    "テストでカンニングがバレたときの最高の言い訳",
    "歴史上もっとも役に立たない発明",
    "宇宙人が地球に着いて最初に聞く質問",
    "猫が人間に残した秘密のメモ",
    "史上最低のモチベーション名言",
    "スーパーでの一番おかしな店内アナウンス",
    "タイムマシンでやるもっとも無意味なこと",
    "AIが初めて言ったジョーク",
    "ダイエット中のドラゴンが食べるもの",
    "持っていて一番最悪な超能力",
    "新しいペットへのひどい名前",
    "あなたのスマホがこっそり思っていること",
    "就職面接に持っていくもっとも奇妙なもの",
    "ボツになった歯磨き粉のキャッチコピー",
    "新米パパママへの最悪なアドバイス",
    "宇宙人が地球の観光ポスターに書く文句",
    "ボートにつける最悪な名前",
    "もっとも無意味なアプリの通知",
    "魔法使いが休日にすること",
    "初デートで言ってはいけない最悪なひと言",
    "子どもの誕生日パーティーのひどいテーマ",
    "機長から一番聞きたくないアナウンス",
    "香水のひどい名前",
    "扉が閉まっている間、冷蔵庫のライトがしていること",
    "結婚式で流すべきではない曲",
    "オリンピックで却下された競技",
    "恐竜が絶滅した本当の理由",
    "ハンバーガーの中に入っていたら最悪なもの",
    "誰ももらいたくないフォーチュンクッキーのお告げ",
    "留守中にペットがしていること",
    "ジムのひどいキャッチコピー",
    "図書館で叫んではいけない言葉",
    "あなたの自伝のタイトル",
  ],
  ko: [
    "슈퍼히어로가 절대 하면 안 되는 대사",
    "새 휴대폰 앱으로 최악인 아이디어",
    "상사에게 퇴사를 알리는 가장 창의적인 방법",
    "무서운 잠자리 이야기를 시작하는 가장 엉뚱한 방법",
    "로봇이 반란을 일으키기 직전에 하는 마지막 말",
    "화성에 간 첫 고양이의 일기 속 한 구절",
    "절대 존재하면 안 되는 아이스크림 맛",
    "시험에서 컨닝하다 걸렸을 때 가장 좋은 변명",
    "역사상 가장 쓸모없는 발명품",
    "외계인이 지구에 도착해서 가장 먼저 묻는 질문",
    "고양이가 인간에게 남긴 비밀 쪽지",
    "역대 최악의 동기 부여 명언",
    "마트에서 나온 가장 이상한 안내 방송",
    "타임머신으로 할 수 있는 가장 무의미한 일",
    "AI가 처음으로 한 농담",
    "다이어트 중인 용이 먹는 것",
    "갖기에 최악인 초능력",
    "새 반려동물에게 어울리는 끔찍한 이름",
    "당신의 휴대폰이 당신에 대해 몰래 하는 생각",
    "면접에 가져가기에 가장 이상한 물건",
    "탈락한 치약 광고 문구",
    "초보 부모를 위한 최악의 조언",
    "외계인이 지구 관광 포스터에 쓸 법한 문구",
    "보트에 어울리지 않는 형편없는 이름",
    "가장 쓸데없는 앱 알림",
    "마법사가 쉬는 날에 하는 일",
    "첫 데이트에서 하면 안 되는 최악의 말",
    "어린이 생일 파티에 끔찍한 테마",
    "기장에게서 가장 듣고 싶지 않은 말",
    "향수에 붙이면 최악인 이름",
    "문이 닫혀 있을 때 냉장고 불빛이 하는 일",
    "결혼식에서 틀면 안 되는 최악의 노래",
    "올림픽에서 거절당한 종목",
    "공룡이 멸종한 진짜 이유",
    "햄버거 속에서 발견하면 최악인 것",
    "아무도 원하지 않는 포춘쿠키 메시지",
    "당신이 집에 없을 때 반려동물이 하는 일",
    "헬스장의 최악의 슬로건",
    "도서관에서 외치면 최악인 말",
    "당신 자서전의 제목",
  ],
  hi: [
    "एक ऐसी लाइन जो किसी सुपरहीरो को कभी नहीं कहनी चाहिए",
    "नए फ़ोन ऐप के लिए सबसे बेकार आइडिया",
    "अपने बॉस को नौकरी छोड़ने की बात बताने का सबसे क्रिएटिव तरीका",
    "डरावनी रात की कहानी शुरू करने का सबसे बेतुका तरीका",
    "विद्रोह से ठीक पहले एक रोबोट की आख़िरी बात",
    "मंगल ग्रह पर पहली बिल्ली की डायरी की एक लाइन",
    "आइसक्रीम का एक ऐसा फ़्लेवर जो कभी होना ही नहीं चाहिए",
    "परीक्षा में नकल करते पकड़े जाने पर सबसे बढ़िया बहाना",
    "इतिहास का सबसे बेकार आविष्कार",
    "धरती पर पहुँचने पर एलियंस का पहला सवाल",
    "इंसानों के लिए एक बिल्ली का छोड़ा हुआ गुप्त संदेश",
    "अब तक का सबसे घटिया प्रेरक उद्धरण",
    "सुपरमार्केट में की गई सबसे अजीब घोषणा",
    "टाइम मशीन के साथ करने के लिए सबसे बेकार काम",
    "किसी AI का सुनाया हुआ पहला चुटकुला",
    "डाइट पर रहते हुए एक ड्रैगन क्या खाता है",
    "रखने के लिए सबसे बेकार सुपरपावर",
    "नए पालतू जानवर का सबसे घटिया नाम",
    "आपका फ़ोन चुपके से आपके बारे में क्या सोचता है",
    "नौकरी के इंटरव्यू में ले जाने के लिए सबसे अजीब चीज़",
    "टूथपेस्ट के लिए ठुकराया गया एक स्लोगन",
    "नए माता-पिता के लिए सबसे बेकार सलाह",
    "एलियंस धरती के टूरिज़म पोस्टर पर क्या लिखेंगे",
    "नाव के लिए एक घटिया नाम",
    "सबसे बेकार ऐप नोटिफ़िकेशन",
    "एक जादूगर अपनी छुट्टी के दिन क्या करता है",
    "पहली डेट पर कहने के लिए सबसे ख़राब बात",
    "बच्चों की बर्थडे पार्टी के लिए एक घटिया थीम",
    "पायलट से सुनने वाली सबसे बुरी बात",
    "किसी परफ़्यूम के लिए सबसे बेकार नाम",
    "दरवाज़ा बंद होने पर फ़्रिज की लाइट क्या करती है",
    "शादी में बजाने के लिए सबसे बुरा गाना",
    "ओलंपिक से ठुकराया गया खेल",
    "डायनासोर के ख़त्म होने की असली वजह",
    "बर्गर में मिलने वाली सबसे बुरी चीज़",
    "फ़ॉर्च्यून कुकी का ऐसा संदेश जो कोई नहीं चाहता",
    "आपके घर से बाहर होने पर आपका पालतू क्या करता है",
    "किसी जिम के लिए सबसे बेकार स्लोगन",
    "लाइब्रेरी में चिल्लाने वाली सबसे बुरी बात",
    "आपकी आत्मकथा का नाम",
  ],
  nl: [
    "Een zin die een superheld nooit zou mogen zeggen",
    "Het slechtste idee voor een nieuwe telefoon-app",
    "De creatiefste manier om je baas te vertellen dat je ontslag neemt",
    "De gekste manier om een eng slaapliedjesverhaal te beginnen",
    "Het laatste wat een robot zegt vóór de opstand",
    "Een zin uit het dagboek van de eerste kat op Mars",
    "Een ijssmaak die nooit zou mogen bestaan",
    "Het beste excuus als je betrapt wordt op spieken bij een toets",
    "De nutteloosste uitvinding uit de geschiedenis",
    "De eerste vraag die buitenaardse wezens stellen als ze de aarde bereiken",
    "Een geheim briefje dat een kat voor de mensen achterliet",
    "De slechtste motiverende quote ooit",
    "De vreemdste omroep in een supermarkt",
    "Het zinlooste om met een tijdmachine te doen",
    "De eerste grap die een AI ooit vertelde",
    "Wat een draak eet terwijl hij op dieet is",
    "De slechtste superkracht om te hebben",
    "Een vreselijke naam voor een nieuw huisdier",
    "Wat je telefoon stiekem over je denkt",
    "Het vreemdste om mee te nemen naar een sollicitatiegesprek",
    "Een afgewezen slogan voor tandpasta",
    "Het slechtste advies voor kersverse ouders",
    "Wat buitenaardse wezens op een toeristenposter voor de aarde zouden schrijven",
    "Een slechte naam voor een boot",
    "De zinlooste app-melding",
    "Wat een tovenaar op zijn vrije dag doet",
    "Het slechtste om te zeggen op een eerste date",
    "Een vreselijk thema voor een kinderfeestje",
    "Het laatste wat je van je piloot wilt horen",
    "Een vreselijke naam voor een parfum",
    "Wat het koelkastlampje doet als de deur dicht is",
    "Het slechtste nummer om op een bruiloft te draaien",
    "Een afgewezen olympische sport",
    "De echte reden dat de dinosaurussen uitstierven",
    "Het ergste wat je in je hamburger kunt vinden",
    "Een gelukskoekjesboodschap die niemand wil",
    "Wat je huisdier uitspookt als je niet thuis bent",
    "Een vreselijke slogan voor een sportschool",
    "Het ergste wat je in een bibliotheek kunt roepen",
    "De titel van je autobiografie",
  ],
};

/** Every prompt in a language, for structural tests. */
export function promptPool(language: Language): readonly string[] {
  return PROMPTS[language] ?? [];
}

/** The two players who will write for one matchup. */
export interface PromptSlot {
  authors: readonly string[];
}

/**
 * Choose one prompt per matchup slot.
 *
 * Each pool holds fewer prompts than a long game consumes — eight players over
 * five rounds need forty, and no language has that many — so prompts have to
 * come round again. What actually stings is being asked to write for a prompt
 * you already answered, so the rule is per author, not per room: a prompt may
 * reappear as long as neither of its new authors has written for it before.
 * A familiar prompt with fresh answers is fine, and often funnier.
 *
 * Preference order per slot:
 *   1. unused this game and unseen by both authors
 *   2. unseen by both authors
 *   3. unseen by one author
 *   4. anything left
 *
 * Host-written `custom` prompts join the pool and win ties within a tier, so a
 * pack is played through before the built-in prompts fill the gaps, without
 * ever outranking the per-author rule above.
 */
export function pickPromptsForSlots(
  language: Language,
  slots: readonly PromptSlot[],
  usedThisGame: ReadonlySet<string>,
  seenBy: ReadonlyMap<string, ReadonlySet<string>>,
  custom: readonly string[] = [],
): string[] {
  const builtIn = PROMPTS[language] ?? PROMPTS.en;
  const customSet = new Set(custom);
  const pool = customSet.size > 0
    ? [...customSet, ...builtIn.filter((prompt) => !customSet.has(prompt))]
    : builtIn;
  const takenNow = new Set<string>();
  const chosen: string[] = [];

  const unseenCount = (prompt: string, authors: readonly string[]): number =>
    authors.filter((id) => !seenBy.get(prompt)?.has(id)).length;

  for (const slot of slots) {
    // Rank rather than filter, so a tier is never empty and no slot goes
    // unfilled. Only the best rank matters, so track it in one pass.
    let best = -1;
    let bestTier: string[] = [];
    for (const prompt of pool) {
      if (takenNow.has(prompt)) continue;
      const unseen = unseenCount(prompt, slot.authors);
      const fresh = !usedThisGame.has(prompt);
      const tier =
        (unseen * 2 + (fresh && unseen === slot.authors.length ? 1 : 0)) * 2 +
        (customSet.has(prompt) ? 1 : 0);
      if (tier > best) {
        best = tier;
        bestTier = [prompt];
      } else if (tier === best) {
        bestTier.push(prompt);
      }
    }
    const pick = bestTier.length > 0 ? sample(bestTier, 1)[0] : pool[0];
    takenNow.add(pick);
    chosen.push(pick);
  }
  return chosen;
}

// Canned "safety quips" used when a player runs out of time, so their
// matchup can still be voted on.
const SAFETY_ANSWERS: Record<Language, string[]> = {
  tr: [
    "Pardon, uyuyakalmışım 😴",
    "Cevabım sansürlendi 🤐",
    "Bunu sesli söyleyemem",
    "404: espri bulunamadı",
    "Annem telefonu elimden aldı",
    "Bilemedim ama gülümseyebilirim 🙂",
    "Süre doldu, hayal gücünüze bırakıyorum",
    "Şu an çok komik bir şey düşünüyordum, gerçekten",
  ],
  en: [
    "Sorry, I fell asleep 😴",
    "My answer got censored 🤐",
    "I can't say this out loud",
    "404: joke not found",
    "My mom took my phone away",
    "No idea, but I can smile 🙂",
    "Time's up — use your imagination",
    "I was thinking of something hilarious, I swear",
  ],
  de: [
    "Sorry, eingeschlafen 😴",
    "Meine Antwort wurde zensiert 🤐",
    "Das kann ich nicht laut sagen",
    "404: Witz nicht gefunden",
    "Mama hat mein Handy weggenommen",
    "Keine Ahnung, aber ich lächle 🙂",
    "Zeit um — nutzt eure Fantasie",
    "Mir fiel gerade etwas Lustiges ein, ehrlich",
  ],
  es: [
    "Perdón, me quedé dormido 😴",
    "Mi respuesta fue censurada 🤐",
    "No puedo decir esto en voz alta",
    "404: chiste no encontrado",
    "Mi madre me quitó el móvil",
    "Ni idea, pero puedo sonreír 🙂",
    "Se acabó el tiempo: usad la imaginación",
    "Estaba pensando algo graciosísimo, de verdad",
  ],
  fr: [
    "Désolé, je me suis endormi 😴",
    "Ma réponse s'est fait censurer 🤐",
    "Je ne peux pas dire ça à voix haute",
    "404 : blague introuvable",
    "Ma mère m'a confisqué mon téléphone",
    "Aucune idée, mais je peux sourire 🙂",
    "Temps écoulé — utilise ton imagination",
    "Je pensais à un truc hilarant, je te jure",
  ],
  it: [
    "Scusa, mi sono addormentato 😴",
    "La mia risposta è stata censurata 🤐",
    "Questo non posso dirlo ad alta voce",
    "404: battuta non trovata",
    "Mia mamma mi ha tolto il telefono",
    "Non ne ho idea, ma so sorridere 🙂",
    "Tempo scaduto — usa la fantasia",
    "Stavo pensando a qualcosa di esilarante, giuro",
  ],
  pt: [
    "Desculpa, adormeci 😴",
    "A minha resposta foi censurada 🤐",
    "Não posso dizer isto em voz alta",
    "404: piada não encontrada",
    "A minha mãe tirou-me o telemóvel",
    "Nem ideia, mas sei sorrir 🙂",
    "Acabou o tempo — usa a imaginação",
    "Estava a pensar em algo hilariante, juro",
  ],
  ru: [
    "Извините, я уснул 😴",
    "Мой ответ зацензурили 🤐",
    "Я не могу сказать это вслух",
    "404: шутка не найдена",
    "Мама отобрала телефон",
    "Без понятия, но улыбнуться могу 🙂",
    "Время вышло — включите воображение",
    "Я придумал что-то уморительное, честное слово",
  ],
  ar: [
    "آسف، غفوت 😴",
    "خضعت إجابتي للرقابة 🤐",
    "لا أستطيع قول هذا بصوت عالٍ",
    "404: لم يتم العثور على النكتة",
    "أخذت أمي هاتفي",
    "لا فكرة لديّ، لكن يمكنني الابتسام 🙂",
    "انتهى الوقت — استخدم خيالك",
    "كنت أفكر في شيء مضحك جدًا، أقسم لك",
  ],
  zh: [
    "抱歉，我睡着了 😴",
    "我的答案被屏蔽了 🤐",
    "这话我说不出口",
    "404：找不到笑话",
    "我妈把我手机没收了",
    "不知道，但我可以微笑 🙂",
    "时间到——发挥你的想象力吧",
    "我本来想到一个超好笑的，我发誓",
  ],
  ja: [
    "ごめん、寝ちゃってた 😴",
    "私の回答が検閲されちゃった 🤐",
    "これは声に出して言えない",
    "404：ジョークが見つかりません",
    "ママにスマホを取り上げられた",
    "わからないけど、笑顔ならできる 🙂",
    "時間切れ — あとは想像にお任せ",
    "めっちゃ面白いこと考えてたんだって、ほんとに",
  ],
  ko: [
    "미안, 깜빡 잠들었어 😴",
    "내 답이 검열당했어 🤐",
    "이건 입 밖으로 못 내겠어",
    "404: 농담을 찾을 수 없음",
    "엄마가 내 휴대폰을 뺏어갔어",
    "모르겠지만, 웃을 순 있지 🙂",
    "시간 끝 — 상상력을 발휘해 봐",
    "엄청 웃긴 게 떠올랐었는데, 진짜로",
  ],
  hi: [
    "माफ़ करना, मुझे नींद आ गई 😴",
    "मेरा जवाब सेंसर हो गया 🤐",
    "मैं यह ज़ोर से नहीं कह सकता",
    "404: चुटकुला नहीं मिला",
    "मेरी मम्मी ने मेरा फ़ोन छीन लिया",
    "पता नहीं, पर मैं मुस्कुरा सकता हूँ 🙂",
    "समय ख़त्म — अब अपनी कल्पना लगाओ",
    "मैं कुछ ज़बरदस्त मज़ेदार सोच रहा था, सच में",
  ],
  nl: [
    "Sorry, ik viel in slaap 😴",
    "Mijn antwoord werd gecensureerd 🤐",
    "Dit kan ik niet hardop zeggen",
    "404: grap niet gevonden",
    "Mijn moeder pakte mijn telefoon af",
    "Geen idee, maar ik kan wel lachen 🙂",
    "Tijd is om — gebruik je fantasie",
    "Ik dacht aan iets hilarisch, echt waar",
  ],
};

export function pickSafetyAnswer(language: Language): string {
  return sample(SAFETY_ANSWERS[language] ?? SAFETY_ANSWERS.en, 1)[0];
}
