import type { Language } from "../../../shared/src/index.js";

// Fill-in-the-blank prompts per language. Players write the funniest answer.
const PROMPTS: Record<Language, string[]> = {
  tr: [
    "Bir süper kahramanın asla söylememesi gereken cümle",
    "Yeni bir telefon uygulaması için en kötü fikir",
    "Patronuna işi bıraktığını söylemenin en yaratıcı yolu",
    "Çocukları korkutacak en saçma masal başlangıcı",
    "Bir robotun isyan etmeden önce söyleyeceği son şey",
    "Marsa giden ilk kedinin günlüğünden bir satır",
    "Asla denenmemiş bir dondurma çeşidi",
    "Sınavda kopya çekerken yakalanınca verilecek en iyi bahane",
    "Tarihteki en gereksiz icat",
    "Uzaylılar Dünya'ya gelince ilk soracakları soru",
    "Bir kedinin insanlara gizlice yazdığı not",
    "En kötü motivasyon sözü",
    "Süpermarkette anons edilecek en garip duyuru",
    "Zaman makinesiyle gidip yapılacak en anlamsız şey",
    "Yapay zekanın ilk şakası",
    "Bir ejderhanın diyet yaparken yediği şey",
    "Sahip olunabilecek en kötü süper güç",
    "Yeni bir evcil hayvana verilecek berbat bir isim",
    "Telefonunun senin hakkında gizlice düşündüğü şey",
    "İş görüşmesine getirilecek en garip şey",
    "Diş macunu için reddedilmiş bir slogan",
    "Yeni anne-babaya verilecek en kötü tavsiye",
    "Uzaylıların Dünya için hazırlayacağı turizm afişi yazısı",
    "Bir tekneye verilecek kötü bir isim",
    "En gereksiz uygulama bildirimi",
    "Bir büyücünün izin gününde yaptığı şey",
    "İlk randevuda söylenecek en kötü şey",
    "Çocuk doğum günü partisi için berbat bir tema",
  ],
  en: [
    "A line a superhero should never say",
    "The worst idea for a new phone app",
    "The most creative way to tell your boss you quit",
    "The silliest way to start a scary bedtime story",
    "The last thing a robot says before the uprising",
    "A line from the diary of the first cat on Mars",
    "An ice cream flavor that should never exist",
    "The best excuse when caught cheating on a test",
    "The most useless invention in history",
    "The first question aliens ask when they reach Earth",
    "A secret note a cat left for humans",
    "The worst motivational quote ever",
    "The strangest announcement at a supermarket",
    "The most pointless thing to do with a time machine",
    "The first joke an AI ever told",
    "What a dragon eats while on a diet",
    "The worst superpower to have",
    "A terrible name for a new pet",
    "What your phone secretly thinks about you",
    "The strangest thing to bring to a job interview",
    "A rejected slogan for toothpaste",
    "The worst advice for new parents",
    "What aliens would write on a tourism poster for Earth",
    "A bad name for a boat",
    "The most pointless app notification",
    "What a wizard does on his day off",
    "The worst thing to say on a first date",
    "A terrible theme for a kids' birthday party",
  ],
  de: [
    "Ein Satz, den ein Superheld niemals sagen sollte",
    "Die schlechteste Idee für eine neue Handy-App",
    "Der kreativste Weg, dem Chef zu kündigen",
    "Der albernste Anfang einer Gruselgeschichte",
    "Das Letzte, was ein Roboter vor dem Aufstand sagt",
    "Eine Zeile aus dem Tagebuch der ersten Katze auf dem Mars",
    "Eine Eissorte, die es nie geben sollte",
    "Die beste Ausrede beim Spicken in der Prüfung",
    "Die nutzloseste Erfindung der Geschichte",
    "Die erste Frage der Außerirdischen auf der Erde",
    "Eine geheime Notiz, die eine Katze Menschen hinterließ",
    "Der schlechteste Motivationsspruch aller Zeiten",
    "Die seltsamste Durchsage im Supermarkt",
    "Das sinnloseste, was man mit einer Zeitmaschine tut",
    "Der erste Witz, den eine KI je erzählte",
    "Was ein Drache isst, wenn er Diät hält",
    "Die schlechteste Superkraft, die man haben kann",
    "Ein schrecklicher Name für ein neues Haustier",
    "Was dein Handy heimlich über dich denkt",
    "Das Seltsamste, was man zu einem Vorstellungsgespräch mitbringt",
    "Ein abgelehnter Slogan für Zahnpasta",
    "Der schlechteste Rat für frischgebackene Eltern",
    "Was Außerirdische auf ein Tourismusplakat für die Erde schreiben",
    "Ein schlechter Name für ein Boot",
    "Die sinnloseste App-Benachrichtigung",
    "Was ein Zauberer an seinem freien Tag macht",
    "Das Schlimmste, was man beim ersten Date sagt",
    "Ein furchtbares Motto für einen Kindergeburtstag",
  ],
  es: [
    "Una frase que un superhéroe nunca debería decir",
    "La peor idea para una nueva app de móvil",
    "La forma más creativa de decirle a tu jefe que renuncias",
    "El inicio más tonto de un cuento de miedo",
    "Lo último que dice un robot antes de la rebelión",
    "Una línea del diario del primer gato en Marte",
    "Un sabor de helado que nunca debería existir",
    "La mejor excusa al ser pillado copiando en un examen",
    "El invento más inútil de la historia",
    "La primera pregunta de los aliens al llegar a la Tierra",
    "Una nota secreta que un gato dejó a los humanos",
    "La peor frase motivacional de la historia",
    "El anuncio más raro en un supermercado",
    "Lo más inútil que harías con una máquina del tiempo",
    "El primer chiste que contó una IA",
    "Qué come un dragón cuando está a dieta",
    "El peor superpoder que se puede tener",
    "Un nombre terrible para una nueva mascota",
    "Lo que tu móvil piensa en secreto sobre ti",
    "Lo más raro que llevar a una entrevista de trabajo",
    "Un eslogan rechazado para una pasta de dientes",
    "El peor consejo para padres primerizos",
    "Lo que los aliens escribirían en un cartel turístico de la Tierra",
    "Un mal nombre para un barco",
    "La notificación de app más inútil",
    "Lo que hace un mago en su día libre",
    "Lo peor que decir en una primera cita",
    "Un tema terrible para una fiesta de cumpleaños infantil",
  ],
};

export function pickPrompts(language: Language, count: number): string[] {
  const pool = PROMPTS[language] ?? PROMPTS.en;
  return [...pool].sort(() => Math.random() - 0.5).slice(0, count);
}
