import type { Language } from "../../../shared/src/index.js";
import { sample } from "../util.js";

export interface TriviaQuestion {
  text: string;
  options: string[];
  correctIndex: number;
}

// Multiple-choice trivia per language. Keep correctIndex in sync with options.
const TRIVIA: Record<Language, TriviaQuestion[]> = {
  tr: [
    { text: "Dünya'nın en büyük okyanusu hangisidir?", options: ["Atlas", "Hint", "Pasifik", "Arktik"], correctIndex: 2 },
    { text: "Mona Lisa'yı kim çizdi?", options: ["Van Gogh", "Leonardo da Vinci", "Picasso", "Michelangelo"], correctIndex: 1 },
    { text: "Bir üçgenin iç açıları toplamı kaç derecedir?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "Hangi gezegen 'Kızıl Gezegen' olarak bilinir?", options: ["Venüs", "Jüpiter", "Mars", "Satürn"], correctIndex: 2 },
    { text: "Türkiye'nin başkenti neresidir?", options: ["İstanbul", "İzmir", "Ankara", "Bursa"], correctIndex: 2 },
    { text: "Suyun kimyasal formülü nedir?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "Hangi hayvan en hızlı kara hayvanıdır?", options: ["Aslan", "Çita", "At", "Ceylan"], correctIndex: 1 },
    { text: "İnsan vücudundaki en büyük organ hangisidir?", options: ["Kalp", "Karaciğer", "Deri", "Beyin"], correctIndex: 2 },
    { text: "Hangi yılda ay'a ilk insan ayak bastı?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "Gökkuşağında kaç renk vardır?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Dünya'da kaç kıta vardır?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Japonya'nın başkenti neresidir?", options: ["Seul", "Pekin", "Tokyo", "Bangkok"], correctIndex: 2 },
    { text: "Bir örümceğin kaç bacağı vardır?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "Doğadaki en sert madde hangisidir?", options: ["Altın", "Demir", "Elmas", "Kuvars"], correctIndex: 2 },
    { text: "Suyun donma noktası kaç °C'dir?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "Güneş'e en yakın gezegen hangisidir?", options: ["Venüs", "Merkür", "Dünya", "Mars"], correctIndex: 1 },
    { text: "Bitkiler hangi gazı emer?", options: ["Oksijen", "Karbondioksit", "Azot", "Hidrojen"], correctIndex: 1 },
    { text: "Bir altıgenin kaç kenarı vardır?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "Mavi ile sarı karışınca hangi renk olur?", options: ["Yeşil", "Mor", "Turuncu", "Kahverengi"], correctIndex: 0 },
    { text: "Çin Seddi hangi ülkededir?", options: ["Hindistan", "Çin", "Japonya", "Kore"], correctIndex: 1 },
  ],
  en: [
    { text: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], correctIndex: 2 },
    { text: "Who painted the Mona Lisa?", options: ["Van Gogh", "Leonardo da Vinci", "Picasso", "Michelangelo"], correctIndex: 1 },
    { text: "What do the interior angles of a triangle add up to?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "Which planet is known as the 'Red Planet'?", options: ["Venus", "Jupiter", "Mars", "Saturn"], correctIndex: 2 },
    { text: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctIndex: 2 },
    { text: "What is the chemical formula for water?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "Which is the fastest land animal?", options: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1 },
    { text: "What is the largest organ in the human body?", options: ["Heart", "Liver", "Skin", "Brain"], correctIndex: 2 },
    { text: "In what year did humans first land on the Moon?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "How many colors are in a rainbow?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "How many continents are there?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "What is the capital of Japan?", options: ["Seoul", "Beijing", "Tokyo", "Bangkok"], correctIndex: 2 },
    { text: "How many legs does a spider have?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "What is the hardest natural substance?", options: ["Gold", "Iron", "Diamond", "Quartz"], correctIndex: 2 },
    { text: "What is the freezing point of water in °C?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "Which planet is closest to the Sun?", options: ["Venus", "Mercury", "Earth", "Mars"], correctIndex: 1 },
    { text: "Which gas do plants absorb?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correctIndex: 1 },
    { text: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "Mixing blue and yellow makes which color?", options: ["Green", "Purple", "Orange", "Brown"], correctIndex: 0 },
    { text: "The Great Wall is in which country?", options: ["India", "China", "Japan", "Korea"], correctIndex: 1 },
  ],
  de: [
    { text: "Was ist der größte Ozean der Erde?", options: ["Atlantik", "Indik", "Pazifik", "Arktik"], correctIndex: 2 },
    { text: "Wer malte die Mona Lisa?", options: ["Van Gogh", "Leonardo da Vinci", "Picasso", "Michelangelo"], correctIndex: 1 },
    { text: "Wie viel ergeben die Innenwinkel eines Dreiecks?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "Welcher Planet ist als 'Roter Planet' bekannt?", options: ["Venus", "Jupiter", "Mars", "Saturn"], correctIndex: 2 },
    { text: "Was ist die Hauptstadt von Australien?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctIndex: 2 },
    { text: "Wie lautet die chemische Formel für Wasser?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "Welches ist das schnellste Landtier?", options: ["Löwe", "Gepard", "Pferd", "Gazelle"], correctIndex: 1 },
    { text: "Was ist das größte Organ des menschlichen Körpers?", options: ["Herz", "Leber", "Haut", "Gehirn"], correctIndex: 2 },
    { text: "In welchem Jahr landeten Menschen erstmals auf dem Mond?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "Wie viele Farben hat ein Regenbogen?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Wie viele Kontinente gibt es?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Was ist die Hauptstadt von Japan?", options: ["Seoul", "Peking", "Tokio", "Bangkok"], correctIndex: 2 },
    { text: "Wie viele Beine hat eine Spinne?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "Was ist die härteste natürliche Substanz?", options: ["Gold", "Eisen", "Diamant", "Quarz"], correctIndex: 2 },
    { text: "Was ist der Gefrierpunkt von Wasser in °C?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "Welcher Planet ist der Sonne am nächsten?", options: ["Venus", "Merkur", "Erde", "Mars"], correctIndex: 1 },
    { text: "Welches Gas nehmen Pflanzen auf?", options: ["Sauerstoff", "Kohlendioxid", "Stickstoff", "Wasserstoff"], correctIndex: 1 },
    { text: "Wie viele Seiten hat ein Sechseck?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "Blau und Gelb gemischt ergibt welche Farbe?", options: ["Grün", "Lila", "Orange", "Braun"], correctIndex: 0 },
    { text: "In welchem Land steht die Chinesische Mauer?", options: ["Indien", "China", "Japan", "Korea"], correctIndex: 1 },
  ],
  es: [
    { text: "¿Cuál es el océano más grande de la Tierra?", options: ["Atlántico", "Índico", "Pacífico", "Ártico"], correctIndex: 2 },
    { text: "¿Quién pintó la Mona Lisa?", options: ["Van Gogh", "Leonardo da Vinci", "Picasso", "Miguel Ángel"], correctIndex: 1 },
    { text: "¿Cuánto suman los ángulos internos de un triángulo?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "¿Qué planeta es conocido como el 'Planeta Rojo'?", options: ["Venus", "Júpiter", "Marte", "Saturno"], correctIndex: 2 },
    { text: "¿Cuál es la capital de Australia?", options: ["Sídney", "Melbourne", "Canberra", "Perth"], correctIndex: 2 },
    { text: "¿Cuál es la fórmula química del agua?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "¿Cuál es el animal terrestre más rápido?", options: ["León", "Guepardo", "Caballo", "Gacela"], correctIndex: 1 },
    { text: "¿Cuál es el órgano más grande del cuerpo humano?", options: ["Corazón", "Hígado", "Piel", "Cerebro"], correctIndex: 2 },
    { text: "¿En qué año el humano pisó la Luna por primera vez?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "¿Cuántos colores tiene un arcoíris?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "¿Cuántos continentes hay?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "¿Cuál es la capital de Japón?", options: ["Seúl", "Pekín", "Tokio", "Bangkok"], correctIndex: 2 },
    { text: "¿Cuántas patas tiene una araña?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "¿Cuál es la sustancia natural más dura?", options: ["Oro", "Hierro", "Diamante", "Cuarzo"], correctIndex: 2 },
    { text: "¿Cuál es el punto de congelación del agua en °C?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "¿Qué planeta está más cerca del Sol?", options: ["Venus", "Mercurio", "Tierra", "Marte"], correctIndex: 1 },
    { text: "¿Qué gas absorben las plantas?", options: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Hidrógeno"], correctIndex: 1 },
    { text: "¿Cuántos lados tiene un hexágono?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "¿Mezclar azul y amarillo da qué color?", options: ["Verde", "Morado", "Naranja", "Marrón"], correctIndex: 0 },
    { text: "¿En qué país está la Gran Muralla?", options: ["India", "China", "Japón", "Corea"], correctIndex: 1 },
  ],
  fr: [
    { text: "Quel est le plus grand océan de la Terre ?", options: ["Atlantique", "Indien", "Pacifique", "Arctique"], correctIndex: 2 },
    { text: "Qui a peint la Joconde ?", options: ["Van Gogh", "Léonard de Vinci", "Picasso", "Michel-Ange"], correctIndex: 1 },
    { text: "Combien font les angles intérieurs d'un triangle au total ?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "Quelle planète est surnommée la « planète rouge » ?", options: ["Vénus", "Jupiter", "Mars", "Saturne"], correctIndex: 2 },
    { text: "Quelle est la capitale de l'Australie ?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctIndex: 2 },
    { text: "Quelle est la formule chimique de l'eau ?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "Quel est l'animal terrestre le plus rapide ?", options: ["Lion", "Guépard", "Cheval", "Gazelle"], correctIndex: 1 },
    { text: "Quel est le plus grand organe du corps humain ?", options: ["Cœur", "Foie", "Peau", "Cerveau"], correctIndex: 2 },
    { text: "En quelle année les humains ont-ils marché sur la Lune pour la première fois ?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "Combien de couleurs y a-t-il dans un arc-en-ciel ?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Combien y a-t-il de continents ?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Quelle est la capitale du Japon ?", options: ["Séoul", "Pékin", "Tokyo", "Bangkok"], correctIndex: 2 },
    { text: "Combien de pattes a une araignée ?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "Quelle est la substance naturelle la plus dure ?", options: ["Or", "Fer", "Diamant", "Quartz"], correctIndex: 2 },
    { text: "Quel est le point de congélation de l'eau en °C ?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "Quelle planète est la plus proche du Soleil ?", options: ["Vénus", "Mercure", "Terre", "Mars"], correctIndex: 1 },
    { text: "Quel gaz les plantes absorbent-elles ?", options: ["Oxygène", "Dioxyde de carbone", "Azote", "Hydrogène"], correctIndex: 1 },
    { text: "Combien de côtés a un hexagone ?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "Mélanger le bleu et le jaune donne quelle couleur ?", options: ["Vert", "Violet", "Orange", "Marron"], correctIndex: 0 },
    { text: "La Grande Muraille se trouve dans quel pays ?", options: ["Inde", "Chine", "Japon", "Corée"], correctIndex: 1 },
  ],
  it: [
    { text: "Qual è l'oceano più grande della Terra?", options: ["Atlantico", "Indiano", "Pacifico", "Artico"], correctIndex: 2 },
    { text: "Chi ha dipinto la Gioconda?", options: ["Van Gogh", "Leonardo da Vinci", "Picasso", "Michelangelo"], correctIndex: 1 },
    { text: "Quanto misura la somma degli angoli interni di un triangolo?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "Quale pianeta è noto come il 'Pianeta Rosso'?", options: ["Venere", "Giove", "Marte", "Saturno"], correctIndex: 2 },
    { text: "Qual è la capitale dell'Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctIndex: 2 },
    { text: "Qual è la formula chimica dell'acqua?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "Qual è l'animale terrestre più veloce?", options: ["Leone", "Ghepardo", "Cavallo", "Gazzella"], correctIndex: 1 },
    { text: "Qual è l'organo più grande del corpo umano?", options: ["Cuore", "Fegato", "Pelle", "Cervello"], correctIndex: 2 },
    { text: "In quale anno l'uomo è atterrato per la prima volta sulla Luna?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "Quanti colori ci sono in un arcobaleno?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Quanti continenti ci sono?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Qual è la capitale del Giappone?", options: ["Seul", "Pechino", "Tokyo", "Bangkok"], correctIndex: 2 },
    { text: "Quante zampe ha un ragno?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "Qual è la sostanza naturale più dura?", options: ["Oro", "Ferro", "Diamante", "Quarzo"], correctIndex: 2 },
    { text: "Qual è il punto di congelamento dell'acqua in °C?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "Quale pianeta è il più vicino al Sole?", options: ["Venere", "Mercurio", "Terra", "Marte"], correctIndex: 1 },
    { text: "Quale gas assorbono le piante?", options: ["Ossigeno", "Anidride carbonica", "Azoto", "Idrogeno"], correctIndex: 1 },
    { text: "Quanti lati ha un esagono?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "Mescolando blu e giallo si ottiene quale colore?", options: ["Verde", "Viola", "Arancione", "Marrone"], correctIndex: 0 },
    { text: "La Grande Muraglia si trova in quale Paese?", options: ["India", "Cina", "Giappone", "Corea"], correctIndex: 1 },
  ],
  pt: [
    { text: "Qual é o maior oceano da Terra?", options: ["Atlântico", "Índico", "Pacífico", "Ártico"], correctIndex: 2 },
    { text: "Quem pintou a Mona Lisa?", options: ["Van Gogh", "Leonardo da Vinci", "Picasso", "Miguel Ângelo"], correctIndex: 1 },
    { text: "Quanto somam os ângulos internos de um triângulo?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "Que planeta é conhecido como o 'Planeta Vermelho'?", options: ["Vénus", "Júpiter", "Marte", "Saturno"], correctIndex: 2 },
    { text: "Qual é a capital da Austrália?", options: ["Sydney", "Melbourne", "Camberra", "Perth"], correctIndex: 2 },
    { text: "Qual é a fórmula química da água?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "Qual é o animal terrestre mais rápido?", options: ["Leão", "Chita", "Cavalo", "Gazela"], correctIndex: 1 },
    { text: "Qual é o maior órgão do corpo humano?", options: ["Coração", "Fígado", "Pele", "Cérebro"], correctIndex: 2 },
    { text: "Em que ano os humanos chegaram pela primeira vez à Lua?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "Quantas cores tem um arco-íris?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Quantos continentes existem?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Qual é a capital do Japão?", options: ["Seul", "Pequim", "Tóquio", "Banguecoque"], correctIndex: 2 },
    { text: "Quantas patas tem uma aranha?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "Qual é a substância natural mais dura?", options: ["Ouro", "Ferro", "Diamante", "Quartzo"], correctIndex: 2 },
    { text: "Qual é o ponto de congelação da água em °C?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "Qual é o planeta mais próximo do Sol?", options: ["Vénus", "Mercúrio", "Terra", "Marte"], correctIndex: 1 },
    { text: "Que gás as plantas absorvem?", options: ["Oxigénio", "Dióxido de carbono", "Azoto", "Hidrogénio"], correctIndex: 1 },
    { text: "Quantos lados tem um hexágono?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "Misturar azul e amarelo dá que cor?", options: ["Verde", "Roxo", "Laranja", "Castanho"], correctIndex: 0 },
    { text: "A Grande Muralha fica em que país?", options: ["Índia", "China", "Japão", "Coreia"], correctIndex: 1 },
  ],
  ru: [
    { text: "Какой океан на Земле самый большой?", options: ["Атлантический", "Индийский", "Тихий", "Северный Ледовитый"], correctIndex: 2 },
    { text: "Кто написал «Мону Лизу»?", options: ["Ван Гог", "Леонардо да Винчи", "Пикассо", "Микеланджело"], correctIndex: 1 },
    { text: "Чему равна сумма внутренних углов треугольника?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "Какую планету называют «Красной планетой»?", options: ["Венера", "Юпитер", "Марс", "Сатурн"], correctIndex: 2 },
    { text: "Какая столица Австралии?", options: ["Сидней", "Мельбурн", "Канберра", "Перт"], correctIndex: 2 },
    { text: "Какова химическая формула воды?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "Какое животное самое быстрое на суше?", options: ["Лев", "Гепард", "Лошадь", "Газель"], correctIndex: 1 },
    { text: "Какой орган самый большой в теле человека?", options: ["Сердце", "Печень", "Кожа", "Мозг"], correctIndex: 2 },
    { text: "В каком году люди впервые высадились на Луну?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "Сколько цветов в радуге?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Сколько на свете континентов?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Какая столица Японии?", options: ["Сеул", "Пекин", "Токио", "Бангкок"], correctIndex: 2 },
    { text: "Сколько ног у паука?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "Какое вещество самое твёрдое в природе?", options: ["Золото", "Железо", "Алмаз", "Кварц"], correctIndex: 2 },
    { text: "Какова температура замерзания воды в °C?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "Какая планета ближе всего к Солнцу?", options: ["Венера", "Меркурий", "Земля", "Марс"], correctIndex: 1 },
    { text: "Какой газ поглощают растения?", options: ["Кислород", "Углекислый газ", "Азот", "Водород"], correctIndex: 1 },
    { text: "Сколько сторон у шестиугольника?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "Какой цвет получится, если смешать синий и жёлтый?", options: ["Зелёный", "Фиолетовый", "Оранжевый", "Коричневый"], correctIndex: 0 },
    { text: "В какой стране находится Великая стена?", options: ["Индия", "Китай", "Япония", "Корея"], correctIndex: 1 },
  ],
  ar: [
    { text: "ما أكبر محيط على وجه الأرض؟", options: ["الأطلسي", "الهندي", "الهادئ", "المتجمد الشمالي"], correctIndex: 2 },
    { text: "من رسم لوحة الموناليزا؟", options: ["فان غوخ", "ليوناردو دافنشي", "بيكاسو", "مايكل أنجلو"], correctIndex: 1 },
    { text: "كم مجموع الزوايا الداخلية للمثلث؟", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "أي كوكب يُعرف بـ'الكوكب الأحمر'؟", options: ["الزهرة", "المشتري", "المريخ", "زحل"], correctIndex: 2 },
    { text: "ما عاصمة أستراليا؟", options: ["سيدني", "ملبورن", "كانبيرا", "بيرث"], correctIndex: 2 },
    { text: "ما الصيغة الكيميائية للماء؟", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "ما أسرع حيوان بري؟", options: ["الأسد", "الفهد", "الحصان", "الغزال"], correctIndex: 1 },
    { text: "ما أكبر عضو في جسم الإنسان؟", options: ["القلب", "الكبد", "الجلد", "الدماغ"], correctIndex: 2 },
    { text: "في أي عام هبط البشر على القمر لأول مرة؟", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "كم لونًا في قوس قزح؟", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "كم عدد القارات؟", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "ما عاصمة اليابان؟", options: ["سيول", "بكين", "طوكيو", "بانكوك"], correctIndex: 2 },
    { text: "كم عدد أرجل العنكبوت؟", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "ما أصلب مادة طبيعية؟", options: ["الذهب", "الحديد", "الماس", "الكوارتز"], correctIndex: 2 },
    { text: "ما درجة تجمّد الماء بالدرجة المئوية؟", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "أي كوكب هو الأقرب إلى الشمس؟", options: ["الزهرة", "عطارد", "الأرض", "المريخ"], correctIndex: 1 },
    { text: "ما الغاز الذي تمتصه النباتات؟", options: ["الأكسجين", "ثاني أكسيد الكربون", "النيتروجين", "الهيدروجين"], correctIndex: 1 },
    { text: "كم عدد أضلاع الشكل السداسي؟", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "مزج الأزرق والأصفر ينتج أي لون؟", options: ["الأخضر", "البنفسجي", "البرتقالي", "البني"], correctIndex: 0 },
    { text: "سور الصين العظيم يقع في أي دولة؟", options: ["الهند", "الصين", "اليابان", "كوريا"], correctIndex: 1 },
  ],
  zh: [
    { text: "地球上最大的海洋是哪个？", options: ["大西洋", "印度洋", "太平洋", "北冰洋"], correctIndex: 2 },
    { text: "《蒙娜丽莎》是谁画的？", options: ["梵高", "列奥纳多·达·芬奇", "毕加索", "米开朗基罗"], correctIndex: 1 },
    { text: "三角形的内角和是多少？", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "哪颗行星被称为“红色星球”？", options: ["金星", "木星", "火星", "土星"], correctIndex: 2 },
    { text: "澳大利亚的首都是哪里？", options: ["悉尼", "墨尔本", "堪培拉", "珀斯"], correctIndex: 2 },
    { text: "水的化学式是什么？", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "陆地上跑得最快的动物是哪种？", options: ["狮子", "猎豹", "马", "瞪羚"], correctIndex: 1 },
    { text: "人体最大的器官是什么？", options: ["心脏", "肝脏", "皮肤", "大脑"], correctIndex: 2 },
    { text: "人类首次登上月球是在哪一年？", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "彩虹有几种颜色？", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "地球上有几大洲？", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "日本的首都是哪里？", options: ["首尔", "北京", "东京", "曼谷"], correctIndex: 2 },
    { text: "蜘蛛有几条腿？", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "最坚硬的天然物质是什么？", options: ["黄金", "铁", "钻石", "石英"], correctIndex: 2 },
    { text: "水的冰点是多少摄氏度（°C）？", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "离太阳最近的行星是哪颗？", options: ["金星", "水星", "地球", "火星"], correctIndex: 1 },
    { text: "植物吸收哪种气体？", options: ["氧气", "二氧化碳", "氮气", "氢气"], correctIndex: 1 },
    { text: "六边形有几条边？", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "蓝色和黄色混合会得到什么颜色？", options: ["绿色", "紫色", "橙色", "棕色"], correctIndex: 0 },
    { text: "长城在哪个国家？", options: ["印度", "中国", "日本", "韩国"], correctIndex: 1 },
  ],
  ja: [
    { text: "地球で最も大きい海は？", options: ["大西洋", "インド洋", "太平洋", "北極海"], correctIndex: 2 },
    { text: "モナ・リザを描いたのは誰？", options: ["ゴッホ", "レオナルド・ダ・ヴィンチ", "ピカソ", "ミケランジェロ"], correctIndex: 1 },
    { text: "三角形の内角の和は？", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "「赤い惑星」と呼ばれているのはどれ？", options: ["金星", "木星", "火星", "土星"], correctIndex: 2 },
    { text: "オーストラリアの首都は？", options: ["シドニー", "メルボルン", "キャンベラ", "パース"], correctIndex: 2 },
    { text: "水の化学式は？", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "陸上で最も速い動物は？", options: ["ライオン", "チーター", "馬", "ガゼル"], correctIndex: 1 },
    { text: "人体で最も大きい臓器は？", options: ["心臓", "肝臓", "皮膚", "脳"], correctIndex: 2 },
    { text: "人類が初めて月に着陸したのは何年？", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "虹は何色？", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "大陸はいくつある？", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "日本の首都は？", options: ["ソウル", "北京", "東京", "バンコク"], correctIndex: 2 },
    { text: "クモの脚は何本？", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "自然界で最も硬い物質は？", options: ["金", "鉄", "ダイヤモンド", "石英"], correctIndex: 2 },
    { text: "水が凍る温度は°Cで何度？", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "太陽に最も近い惑星は？", options: ["金星", "水星", "地球", "火星"], correctIndex: 1 },
    { text: "植物が吸収する気体は？", options: ["酸素", "二酸化炭素", "窒素", "水素"], correctIndex: 1 },
    { text: "六角形の辺はいくつ？", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "青と黄色を混ぜると何色になる？", options: ["緑", "紫", "オレンジ", "茶色"], correctIndex: 0 },
    { text: "万里の長城があるのはどの国？", options: ["インド", "中国", "日本", "韓国"], correctIndex: 1 },
  ],
  ko: [
    { text: "지구에서 가장 큰 바다는 무엇일까요?", options: ["대서양", "인도양", "태평양", "북극해"], correctIndex: 2 },
    { text: "모나리자를 그린 사람은 누구일까요?", options: ["반 고흐", "레오나르도 다빈치", "피카소", "미켈란젤로"], correctIndex: 1 },
    { text: "삼각형 내각의 합은 얼마일까요?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "'붉은 행성'으로 알려진 행성은 무엇일까요?", options: ["금성", "목성", "화성", "토성"], correctIndex: 2 },
    { text: "오스트레일리아의 수도는 어디일까요?", options: ["시드니", "멜버른", "캔버라", "퍼스"], correctIndex: 2 },
    { text: "물의 화학식은 무엇일까요?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "육지에서 가장 빠른 동물은 무엇일까요?", options: ["사자", "치타", "말", "가젤"], correctIndex: 1 },
    { text: "인체에서 가장 큰 장기는 무엇일까요?", options: ["심장", "간", "피부", "뇌"], correctIndex: 2 },
    { text: "인류가 처음 달에 착륙한 해는 언제일까요?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "무지개는 몇 가지 색으로 이루어져 있을까요?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "대륙은 모두 몇 개일까요?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "일본의 수도는 어디일까요?", options: ["서울", "베이징", "도쿄", "방콕"], correctIndex: 2 },
    { text: "거미의 다리는 몇 개일까요?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "천연 물질 중 가장 단단한 것은 무엇일까요?", options: ["금", "철", "다이아몬드", "석영"], correctIndex: 2 },
    { text: "물의 어는점은 섭씨 몇 도일까요?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "태양에서 가장 가까운 행성은 무엇일까요?", options: ["금성", "수성", "지구", "화성"], correctIndex: 1 },
    { text: "식물이 흡수하는 기체는 무엇일까요?", options: ["산소", "이산화탄소", "질소", "수소"], correctIndex: 1 },
    { text: "육각형의 변은 몇 개일까요?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "파란색과 노란색을 섞으면 무슨 색이 될까요?", options: ["초록색", "보라색", "주황색", "갈색"], correctIndex: 0 },
    { text: "만리장성은 어느 나라에 있을까요?", options: ["인도", "중국", "일본", "한국"], correctIndex: 1 },
  ],
  hi: [
    { text: "धरती का सबसे बड़ा महासागर कौन सा है?", options: ["अटलांटिक", "हिंद", "प्रशांत", "आर्कटिक"], correctIndex: 2 },
    { text: "मोनालिसा की पेंटिंग किसने बनाई थी?", options: ["वैन गॉग", "लियोनार्डो दा विंची", "पिकासो", "माइकल एंजेलो"], correctIndex: 1 },
    { text: "त्रिभुज के भीतरी कोणों का योग कितना होता है?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "किस ग्रह को 'लाल ग्रह' कहा जाता है?", options: ["शुक्र", "बृहस्पति", "मंगल", "शनि"], correctIndex: 2 },
    { text: "ऑस्ट्रेलिया की राजधानी क्या है?", options: ["सिडनी", "मेलबर्न", "कैनबरा", "पर्थ"], correctIndex: 2 },
    { text: "पानी का रासायनिक सूत्र क्या है?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "सबसे तेज़ दौड़ने वाला ज़मीनी जानवर कौन सा है?", options: ["शेर", "चीता", "घोड़ा", "हिरण"], correctIndex: 1 },
    { text: "मानव शरीर का सबसे बड़ा अंग कौन सा है?", options: ["हृदय", "जिगर", "त्वचा", "मस्तिष्क"], correctIndex: 2 },
    { text: "इंसान पहली बार चाँद पर किस साल उतरा था?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "इंद्रधनुष में कितने रंग होते हैं?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "दुनिया में कितने महाद्वीप हैं?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "जापान की राजधानी क्या है?", options: ["सियोल", "बीजिंग", "टोक्यो", "बैंकॉक"], correctIndex: 2 },
    { text: "मकड़ी की कितनी टाँगें होती हैं?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "सबसे कठोर प्राकृतिक पदार्थ कौन सा है?", options: ["सोना", "लोहा", "हीरा", "क्वार्ट्ज़"], correctIndex: 2 },
    { text: "पानी का हिमांक °C में कितना होता है?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "सूर्य के सबसे नज़दीक कौन सा ग्रह है?", options: ["शुक्र", "बुध", "पृथ्वी", "मंगल"], correctIndex: 1 },
    { text: "पौधे कौन सी गैस सोखते हैं?", options: ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "हाइड्रोजन"], correctIndex: 1 },
    { text: "षट्भुज की कितनी भुजाएँ होती हैं?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "नीला और पीला मिलाने से कौन सा रंग बनता है?", options: ["हरा", "बैंगनी", "नारंगी", "भूरा"], correctIndex: 0 },
    { text: "विशाल दीवार (ग्रेट वॉल) किस देश में है?", options: ["भारत", "चीन", "जापान", "कोरिया"], correctIndex: 1 },
  ],
  nl: [
    { text: "Wat is de grootste oceaan op aarde?", options: ["Atlantische Oceaan", "Indische Oceaan", "Grote Oceaan", "Noordelijke IJszee"], correctIndex: 2 },
    { text: "Wie schilderde de Mona Lisa?", options: ["Van Gogh", "Leonardo da Vinci", "Picasso", "Michelangelo"], correctIndex: 1 },
    { text: "Hoeveel is de som van de binnenhoeken van een driehoek?", options: ["90", "180", "270", "360"], correctIndex: 1 },
    { text: "Welke planeet staat bekend als de 'Rode Planeet'?", options: ["Venus", "Jupiter", "Mars", "Saturnus"], correctIndex: 2 },
    { text: "Wat is de hoofdstad van Australië?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctIndex: 2 },
    { text: "Wat is de chemische formule voor water?", options: ["CO2", "H2O", "O2", "NaCl"], correctIndex: 1 },
    { text: "Welk landdier is het snelst?", options: ["Leeuw", "Cheeta", "Paard", "Gazelle"], correctIndex: 1 },
    { text: "Wat is het grootste orgaan van het menselijk lichaam?", options: ["Hart", "Lever", "Huid", "Hersenen"], correctIndex: 2 },
    { text: "In welk jaar landden mensen voor het eerst op de maan?", options: ["1959", "1969", "1979", "1989"], correctIndex: 1 },
    { text: "Hoeveel kleuren heeft een regenboog?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Hoeveel continenten zijn er?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { text: "Wat is de hoofdstad van Japan?", options: ["Seoul", "Peking", "Tokio", "Bangkok"], correctIndex: 2 },
    { text: "Hoeveel poten heeft een spin?", options: ["6", "8", "10", "12"], correctIndex: 1 },
    { text: "Wat is de hardste natuurlijke stof?", options: ["Goud", "IJzer", "Diamant", "Kwarts"], correctIndex: 2 },
    { text: "Wat is het vriespunt van water in °C?", options: ["0", "32", "100", "-10"], correctIndex: 0 },
    { text: "Welke planeet staat het dichtst bij de zon?", options: ["Venus", "Mercurius", "Aarde", "Mars"], correctIndex: 1 },
    { text: "Welk gas nemen planten op?", options: ["Zuurstof", "Koolstofdioxide", "Stikstof", "Waterstof"], correctIndex: 1 },
    { text: "Hoeveel zijden heeft een zeshoek?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "Blauw en geel mengen geeft welke kleur?", options: ["Groen", "Paars", "Oranje", "Bruin"], correctIndex: 0 },
    { text: "De Chinese Muur ligt in welk land?", options: ["India", "China", "Japan", "Korea"], correctIndex: 1 },
  ],
};

export function pickTrivia(language: Language, count: number): TriviaQuestion[] {
  return sample(TRIVIA[language] ?? TRIVIA.en, count);
}
